---
title: Undergraduate research at UofT 
description: |
  Links to some pretty sweet resources, stuff to know when looking for research positions, and some observations
preview: gerstein interior heritage.jpg
date: 11-08-2021
author: Cait Harrigan
categories:
  - soap box
output: 
  distill::distill_article:
    self_contained: false
    toc: true
repository_url: https://github.com/harrig12/caitharrigan.ca
creative_commons: CC BY-NC
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Resources for undergraduate research

Before I launch into my own thoughts, I must promote some of the excellent advice that others have compiled. This is a small selection of my personal favourites, but many of them link out to even more resources. This list is aimed primarily at students interested in computational biology & ML - and the rest of the post will follow suit. 

-   [RUCS](https://rucs.ca/) and their fabulous [Undergraduate Research Guide](https://rucs.ca/assets/info/Undergraduate-Research-Guide.pdf)

-   The [BCBSU](https://www.facebook.com/BCBSU.UofT) hosts and annual information session on research courses BCB330 & BCB430

-   [Tips on finding a supervisor](https://bcb.csb.utoronto.ca/bcb430y-project/tips-on-finding-a-supervisor/) from the BCB program

-   [Project X](https://www.uoft.ai/projectx) machine learning research competition



# Research comes in many shapes and sizes

As usual, I will apply the disclaimer that I am only speaking from my own experience, and it's been a while since I was doing undergraduate research myself, so no guarantees that things are the same as they once were.

As an undergrad, I was in the Bioinformatics and Computational Biology program at UofT, 2015-2019. As part of the requirements for that program, there are two research project courses; BCB330 and BCB430. There are many similar courses offered through a variety of programs, such as ROPs, capstone projects, independent research projects, etc. Most of these are blank-cheque style courses you get credit for by working with a professor in a research capacity. 


<aside> 
Often, you don't *have* to be enrolled in a program to take their research course. You can inquire into research offerings in departments such as CSC, STA, MGY, BCH, CSB, and more.
</aside>

Sometimes you can get a paid research position, supported by a [USRA](https://www.nserc-crsng.gc.ca/students-etudiants/ug-pc/usra-brpc_eng.asp) grant. It's a big frustration of mine that I didn't know about USRA's until it was too late. These are grants offered by the Canadian government to support and encourage labs to hire undergraduate students for summer research positions. Don't apply on your own! The proposal expectations are particular, and field-specific. Ask your mentor for help with crafting the application.



# Choose a lab

Most departments have a list of faculty, this is a good place to start. Survey the landscape of professors that you might work with by skimming through their google scholar profile. An easy way to find more, similar labs is to click through their co-authors.

For an interdisciplinary field such as computational biology, I found it useful to look through the faculty pages of multiple departments, various hospital labs, and start-ups that I knew my peers had done research or PEY at.

# Cold contacting

There are many resources out there for how to compose the dreaded "cold email", some that I've linked to [below](\#more-resources). Briefly, here is the anatomy of the cold emails I have sent:

-   introduce yourself
-   explain what kind of position your looking for
-   mention one thing in their recent publication record or lab website that made their lab stick out to you
-   describe any relevant past experience you have
-   ask for an interview
-   attach a cover letter (optional, the email itself may serve as this)
-   attach your CV
-   attach your transcripts

<aside>

Attach your transcripts even if you think they look bad. (I certainly felt this way!) This will increase the likelihood that you hear back and make things go faster. The grades themselves are not usually particularly important, but attaching the transcript is a simple indicator that you understand what this type of email should contain.

</aside>

Professors are often very busy, and often bad at responding to emails. Send these emails out in batches, and if you don't hear back from anyone after about a week, follow up or move on. Radio silence is common, so don't be discouraged by it.

# Don't work for free!

I'll say it again: don't work for free!

This seems to be more of a problem in the wet-lab world than computational labs, but even so I have seen instances of students being taken advantage of via "unpaid internships" or "laboratory volunteer" positions. For one thing, this is not legal in Canada. Perhaps more significantly, it's a big red flag that your work is not being valued as it should be. Chances are that there is a more suitable position out there for you that will serve you better, and compensate you fairly.

You should either get course credit, or a paycheck for your time. (If you can swing it, get both!) Don't underestimate the value of your contributions as an undergraduate researcher. Potentially getting authorship on a publication is not payment.

# What to expect in the research environment

I divide labs into two categories: New PI/Old PI. A New PI is someone who has recently started their lab, they are not super established yet, their group is small, they probably don't have a ton of extra money to spend on paying you. This environment will be good for a course-credit experience, or one where you "bring" your own funding (ex. through a USRA). Although you may be working with a grad student, this PI will probably be more hands-on, and could be directly involved in your project and giving you guidance.

Old PI has seen it all. They are well established, their group is large, and they have lots of high-impact publications. They might have grant money to straight out hire you as an intern. A grad student will be your direct supervisor, and you might not meet with Old PI very frequently.

Obviously the New PI/Old PI caricature is not all-encompassing, and every environment will have its own peculiarities, advantages, and disadvantages. In all cases you will most likely have a chance to interact with grad students, and find out what makes them so dang jaded. You will get to attend (often weekly scheduled) group meetings, and possibly be expected to present your work to the lab at group meeting.

In the most general of terms, the grading for research project courses is relatively lax. Often there is a performance evaluation that your supervisor has to fill out at the end, plus some written or presentation-based deliverable. Many labs mark pretty easy, as long as you fulfill the minimum expectations of showing up and trying hard.

<aside>

Again: No guarantees! Your PI may be a tough marker.

</aside>

# How important is it to publish in undergrad?

Depends on your exact field, but my feeling is: it's not super important. At the undergraduate level, having a publication is less significant than having refined research skills, and being able to describe the work you have done. Research ability is something that tends to come through in an interview, but less clearly on paper. Depending on what kinds of applications you foresee in your future, a publication may be more or less valuable to you.

Of course, a useful skill to have is experience in publishing and communicating results. The best kind of research experience is one where you learn a lot, and get to contribute to a publication. However, this is not usually guaranteed. If the project as a whole is not yet at a place where you can submit to a conference or journal, something you can do at the end of a research experience to make it go a little further is to submit to an undergraduate journal or poster session. Leave a couple weeks at the end of your research experience for developing a write up or poster, and ask your mentor for input. With an end product that you deliver in someway to an audience, you will gain a lot more out of your experience, and make it much easier to write about on your CV.

Some examples of UofT student journals are: [Arbor](https://assu.ca/wp/arbor/), [JULS](https://juls.ca/), [RUCS](%5B%5Bhttps://rucs.c%5D(https://rucs.ca)a%5D(https://rucs.c)). There are several undergraduate research conferences and poster competitions run by various departments, often associated with their respective project courses. The ASSU hosts an annual [undergraduate research conference](https://assu.ca/wp/2021/01/19/join-us-for-the-2021-undergraduate-research-conference/). You can apply to have your research appear in similar venues at other institutes, or if you're particularly ambitious, grab some friends and host your own research day. There are a lot of options for turning course work into an opportunity for research dissemination.

<aside>

Many academic CVs have a "research dissemination" (or equivalent) section. Regardless of whether it was peer reviewed: a publication, presentation, or poster can be a valuable line for you to add to your CV. I like to this of it as similar to the "projects" section that an industry CV might contain.

</aside>

<!--
# Acknowledgments {.appendix}

Thanks to [reviewer]() for proofreading and thoughful suggestions on the initial version of this post.
-->
