---
title: "Gradschool secrets"
description: |
  Things to know when appling to gradschool: how to pick a graduate program, and what professors are looking for in prospective students. 
preview: preview.png
date: 08-28-2021
author: Cait Harrigan
categories:
  - gradschool
  - soap box
output: 
  distill::distill_article:
    self_contained: false
    toc: true
repository_url: https://github.com/harrig12/caitharrigan.ca
creative_commons: CC BY-NC
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Pretty much every student-academic website I see has some version of this post. There are two things that I think drive this fact.

1.  Many academic website themes include a blog section, which makes people feel like they should write something in it. Gradstudents write what they know, and what they know is gradschool.
2.  We're still reeling from the application process. It's confusing, and varies wildly from school-to-school, or even between departments at the same school. Most undergrads have a nebulous understanding of what the people reading their application are looking for, and the process can be heavily influenced by having existing relationships with professors in program.

To me, this second remark is glaring. It points to an accessibility issue for prospective students that don't have gradstudents or professors they can reach out to to get advice on applying[^1]. Now that applying to gradschool is in my rearview mirror, I know a bunch of secrets that I will share with you.

[^1]: Feel free to reach out to *me* for advice, I am happy to be your gradschool friend

## Disclaimer

To remark \#1: I'm writing what I know. What I've learned may only be applicable to the Canadian university experience (although I suspect much of it could be extended to the US). This advice is in general aimed towards students applying to computational, research-based graduate programs. It's more or less a compilation of answers to common questions I've been asked over the last few years. However, these answers come from my personal experiences and may be particular to my career path. Take away what is useful, and leave the rest!

## What to consider when choosing a program

In my opinion, while some programs have nice benefits that others don't, the lab group and advisor that you work with will make a much bigger impact on your grad school experience. Put high weight on *who* is part of the program, in addition to what the program offers.

### Graduate programs are not like undergrad

As a grad student, you will have a direct advisor, who is going to invest time into your progress. Because of this, faculty members have a lot more say in who is admitted to a grad program than undergrad.

In some ways, the bar to get into a grad program may be lower than undergrad. There is generally more wiggle room on grades, and previous research experience counts for a lot. You really only have to convince a professor that you are someone who will be a good fit for their group, and who will learn how to be a researcher.

All this being said, the number one thing you should do when applying to grad school is reach out to professors you might end up working with.

Adjust your expectations. There is a decent chance that you can get admitted to a higher caliber graduate program than you might think. Aim high, and apply to at least one "reach" (ideally more than one).

### Masters to PhD vs Direct Entry

The question on whether to do a Masters program with intent to transfer into a PhD, vs direct entry PhD comes up a lot. In my opinion, it doesn't matter. There seems to be some idea that direct entry is somehow more prestegious than MSc to PhD (maybe because the minimum requirements are different?). No one I've met cares about this at all.

I will comment that a direct entry PhD is often a \>5 year program. This is a big commitment! I did a MSc to PhD transition, and I really appreciated having an opportunity at the end of the masters to reflect on whether research was something I really wanted to continue with. (it is!)

On the other hand, masters projects are often relatively small. You won't get your research rolling in the same way you would in a direct entry program.

### Pooled entry vs assigned advisor {#pooled-entry-vs-assigned-advisor}

Many times you will be admitted into a program, and not assigned an advisor right away. I call this "pooled entry". There are benefits to this: lots of programs have a rotation year, to let you try out different labs, then you pick one you like. However, there is the risk that you don't end up with an advisor you want to work with, and it kind of sucks to spend a whole year in a program, only to find out that things don't go your way in this respect.

At UofT, the Computer Science department takes the other approach: you will not be accepted into the program unless there is a specific professor who is willing to fund you. This means that you know right away when you're accepted who your advsor will be. I liked this because it let me start researching earlier.

<aside>

With the exception of the theory group within computer science, who do a rotation year.

</aside>

### Program requirements

Think about what your program will make you do. What kinds of courses will you be required to take? What will you be missing out on? You can of course always pick up a textbook and run a course for yourself, but if you're anything like me, that's not going to happen.

Pick a program that will *require* you to learn the things that you want to learn over the course of your degree.

## What to consider when choosing a lab

### Read past work

Survey to find out not only what areas of expertise your potential advisor has, but also what kinds of projects they are able to support. What venues do they publish in? Who are their frequent collaborators? What datasets do they tend to favour?

Look out for indicators of what habits you might pick up from the lab. Do they publish reproducible work? Is their github beautiful? Do new papers get a tweetorial?

### Talk to current students

The reason for this is two fold: firstly, current students know the most and they know it now. Information about a lab tends to expire quickly, as members leave and join. Current students are in the loop, and will (almost always) give you honest and helpful answers to your questions.

Secondly, if you join their lab, these current students will be your peers and your mentors. Think about probing questions you can ask that will give you a sense of their style, as well as to learn more about the lab in general.

What do they like about the institute? What do they dislike? What courses do they recommend? What are the strengths and weaknesses of their advisor? What is the lab culture like? Who do they talk to when they're stuck on a problem? How independently are they expected to conduct their work? How often do they meet with their advisor? How hands on is the advisor? Do they have a co-advisor, and how do they manage that relationship? What does their advisor do to support them outside of their research?

In my experience, lab culture is really important. Having both casual and professional access to senior students has definitively shaped how I approach research.

### Interview the professor

I like to think of grad school as an apprenticeship. Your advisor is not your boss, so much as a mentor and will inevitably shape you into being the kind of researcher that they are. Think about whether their style is something you want to emulate. What attributes do they exhibit that you might pick up on? What and they habits and values will they instill in you?

Some questions I really like to ask are:

> Lab direction: what vision do you have for your lab in the next 5 years? What big-picture problems are you tackling?

This is the kind of question that professors have to address when writing grants, so they should have an answer.

> What do you do to foster a positive lab culture?

This will be revealing as to whether your potential advisor actively cultivates a supportive environment.

> What makes for a truly excellent grad student?

This will give you an idea of their expectations, and also probably some useful advice!

<aside>

If you get any really great advice, consider sharing it with me so I can add it to [my previous post about this question](https://caitharrigan.ca/posts/2021-05-04-how-to-be-a-good-grad-student/) `r emo::ji('smile')`

</aside>

## Things that may affect your acceptance chances, that have nothing to do with the application

**This section is still in rough shape**

(Aka: the myth of meritocracy)

There are a handful of external factors that might affect the chances of your application being accepted. Some of them may be more or less exaggerated based on the [type of pool](#pooled-entry-vs-assigned-advisor) you apply to.

### Pre-established relationships with faculty members

Unsurprisingly, having connections is useful. Even a very simple introductory email can go a long way. Here are some things you can do to build a relationship with professors, some of whom might have a hand in admitting you, and all of whom will have useful advice for your application. Some of these things have to be done \>12 months in advance of considering graduate programs, which can be daunting. However, many of them will arise naturally for you in some way, so I hope that this list will help make you aware of instances where you could be taking advantage of an opportunity presenting itself.

From least investment to most:

1.  Cold email

    -   reach out to faculty, ask for informational interview, have some portforlio of past work to show off/talk about

2.  Get to know them through taking their class

    -   depending on the size of your classes, this may be more or less feasible
    - I went to grad school at the same institute that I did my undergrad at and this was feasible for my bachelors thesis course
    - However most of my other classes had hundreds of people in them and close to zero chance of interacting with faculty. This made getting reference letters challenging.

3.  Network at events/conferences

    - it's hard for undergrads to do this, but if you have the warewithal to, excellent. 
    - a lot more obtainable for masters students

4.  Summer internship
    
    - especially if you're coming from industry, you can be a real asset to hire into a lab tech position
    - this is a good way to get to know your research environment, or make connections with the peers of the faculty you want to work with. 

5.  Collaborate
    
    - really good if you're coming from masters
    - also good if you're based in a different country from where you're applying to


### People don't recognize your school name

- more of a problem in the states, apparently smaller schools in canada are attributed higher pedigree than small schools in the states

### Someone called "dibs" on you

- could come into play in the pooled entry format, to improve your chances
- faculty at location A might have friends at another institution B you're applying to. If prof at B mentions they really want you, prof at A might not try too hard to recruit you. 


### Something random in your CV appeals to the reader

- maybe you are an avid skateborder or bird watcher or did a side project that a prof did very similar work on. Maybe there is shared educational history or ... <find a better example than fraternities dear god> . Don't discount the human factor behind the application. 
- good to have a cohesive story about yourself that shines through, but sometimes there is a small random detail that makes you memorable.

### Sheer randomness

- idk dude

<!-- 
## How to mitigate the accessibility issue

This is probably a separate post, especially depending on whether I find that twitter thread or 

but all the stuff I mention assumes a pretty high level of access to resources. 
-->

