---
title: Research
format:
  html:
    toc: true
    toc_float: true
    toc-location: left
---

```{r, echo=F, warning=F, message=F}
options(knitr.kable.NA = '')
source('formatter.R')


cv_entries <- cv_entries %>% filter(website_show == T)
```

<!-- # Software -->

<i class="ai ai-open-access ai-lg"></i> Indicates open access &nbsp;&nbsp; \* Indicates equal contribution &nbsp;&nbsp; <a href="files/harrigan.bib" class="btn btn-secondary icon-link"><i class="fa-solid fa-download fa-sm"></i> Download all as BibTeX</a> 

# Peer Reviewed Publications
 
```{r, echo=F, warning=F, message=F}

pubs <- pub_entries %>% filter(peer_reviewed == T)


tibble(text = apply(pubs,1,make_pub), image = apply(pubs,1,make_image)) %>%
  kable(escape = F, col.names = NULL) %>%
  kable_paper(html_font = "\"Open Sans\",  sans-serif") %>%
  column_spec(2, width_max = "20em", width_min = "10em")


```

# Other Publications

```{r, echo=F, warning=F, message=F}
pubs <- pub_entries %>% filter(peer_reviewed == F)


tibble(text = apply(pubs,1,make_pub), image = apply(pubs,1,make_image)) %>%
  kable(escape = F, col.names = NULL) %>%
  kable_paper(html_font = "\"Open Sans\",  sans-serif") %>%
  column_spec(2, width_max = "20em", width_min = "10em")


```

# Posters

`r print_section(cv_entries, "poster")`
