---
title: "Advice a postdoc gave me"
description: |
  Simple tips for computational biologists
preview: preview.jpg
date: 03-21-2020
author: Cait Harrigan
categories:
  - gradschool
output: 
  distill::distill_article:
    self_contained: false
    toc: true
repository_url: https://github.com/harrig12/caitharrigan.ca
creative_commons: CC BY-NC
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[This article](https://doi.org/10.1073/pnas.1912488116) got posted in my lab's slack. It claims the folowing: 

> Conventional wisdom in the laboratory sciences suggests that PhD students develop their research skills as a function of mentorship from their faculty advisors (i.e., principal investigators; PIs). However, no prior research has identified empirically a relationship between specific PI practices and the development of research skills. Here we show that PIs’ laboratory and mentoring activities do not significantly predict students’ skill development trajectories, but the engagement of postdocs and senior graduate students in laboratory interactions do. These findings support the practice of “cascading mentorship” as differentially effective and identify a critical but previously unrecognized role for postdocs in the graduate training process. They also illustrate both the importance and the feasibility of identifying evidence-based practices in graduate education.

A postdoc in my lab responded, with their wisdom:

+ use tmux
+ use Snakemake
+ use Pycharm
+ use zsh
+ don’t use Jupyter Notebooks
+ use conda environments

This list has served me well so far. To add some wisdom of my own:

+ always write a readme
+ use vscode


